### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by undergroundtheater** [wastevens/ElysiumFrontend#1]
Steps to recreate:

1) Go to UAT site and attempt to create account:
   http://elyu1.undergroundtheater.org:8080/login
2) Fill out form (all fields)
3) Submit form

Get 403

**Comment by undergroundtheater** [comment]
note, fully aware this is likely a configuration issue, but if so, it should be documented as a gotcha at the very least. :)

**Comment by undergroundtheater** [comment]
Note: account IS created, but it appears it's not counting me as "authenticated" after the post processes.

**Comment by wastevens** [comment]
Fixed.
