### ISSUE TITLE
unable to create patronage

### ISSUE THREAD

**Issue by undergroundtheater** [wastevens/ElysiumFrontend#12]
Existing patronages in the db can be assigned (re-assigned?? I hope not), but we still cannot create a new patronage on a brand new user. 

Steps:

1) Create new user (do not set any optional fields)
2) Login as admin
3) Manage Users
4) Add new patronage to user (fails)

tried with the added expiration field that pops up and without, would not save.

I suggested closing #2 a bit hastily, but this is a different issue than was described there.  An admin should be able to click the user, type in the date of the purchase, choose paypal, put in the amount and paste in the receipt number and hit submit.  The expiration should auto-calculate on submit (and should be a hidden field until they have one), but we need to be able to adjust it afterwards (as we already can) in case they donated / renewed "early".

**Comment by wastevens** [comment]
Fixed.
