### ISSUE TITLE
Patron Management Functionality

### ISSUE THREAD

**Issue by ut-secretary** [wastevens/ElysiumFrontend#13]
Means to leave an admin-only visibility note concerning activation and deactivation of patronage status would be very helpful. Particularly to note why a person's expiration date is shortened in the case of disciplinary action/club expulsion.

**Comment by ut-secretary** [comment]
Also, means to search a list of patrons by name, email address, or expiration date.

Means to generate a list of active and/or inactive patrons in so sort of spreadsheet (for on-site verification at conventions, for example).

**Comment by wastevens** [comment]
Milestones created, closing.
