### ISSUE TITLE
Unable to add patronage to account

### ISSUE THREAD

**Issue by undergroundtheater** [wastevens/ElysiumFrontend#2]
I cannot find a way to actually make a patron active in the current interface.  I do not seem to be able to update their expiration date, either.

**Comment by wastevens** [comment]
Process to make a patron active via the UI:
* Login as an admin.
* Go to User Management.
* Select a user from the dropdown.
* If they are not presently a patron, assign them a patronage id (either an existing unassigned one or a new one).  If they are presently a patron, skip this step.
* Enter their Patronage Expiration in yyyy-MM format
* Submit.

![step1](https://cloud.githubusercontent.com/assets/1065558/8144594/73a39534-11b3-11e5-92fe-00528d83ca8e.gif)
![step2](https://cloud.githubusercontent.com/assets/1065558/8144595/7540ebbc-11b3-11e5-84df-26165934c992.gif)
![step3](https://cloud.githubusercontent.com/assets/1065558/8144596/769c58d4-11b3-11e5-9c01-9746f0f5760a.gif)
![step4](https://cloud.githubusercontent.com/assets/1065558/8144598/77d5e45e-11b3-11e5-8f39-5609779847db.gif)

**Comment by undergroundtheater** [comment]
Still will not update expiration date as of commit 18c38f6

**Comment by undergroundtheater** [comment]
Correction, it forces the date to be the 1st of whatever month you put in.  I'd rather have it be the last day of the month if we're going to do this, but all-around, we should be able to set the day of expiration.

**Comment by wastevens** [comment]
Setting it to the day of expiration is easy enough; I didn't know if that level of granularity made sense.  It'll be changed on the next update.

**Comment by undergroundtheater** [comment]
Thanks!  Can you provide basic instructions over the dev list on how someone can help with the JSP changes?  Don't need to give github howto, but knowing the path to the project on github + where the JSP templates are stored should be enough.  if there's any documentation for the JSP taglibs you're using, please provide this as well.

Once we can set the day, we'll be able to close this.

**Comment by wastevens** [comment]
Able to set the day.  Closing.
