### ISSUE TITLE
plaintext password storage

### ISSUE THREAD

**Issue by undergroundtheater** [wastevens/ElysiumFrontend#3]
should make this a priority for a "release" milestone.

**Comment by undergroundtheater** [comment]
Closing, should be [Elysium](/wastevens/Elysium)

**Comment by undergroundtheater** [comment]
Re-opening to let @wastevens decide where this goes.

**Comment by wastevens** [comment]
Closed.  Passwords are now encrypted.  Site wide password encryption secret is NOT committed.
