### ISSUE TITLE
provide way to separate web pages using app.properties

### ISSUE THREAD

**Issue by undergroundtheater** [wastevens/ElysiumFrontend#4]
Can we either have the JSP's capable of being stored separately or at least provide a way to use a template for the actual frontend developers (HTML, CSS + jquery / js) to begin work on the interface?

I think app.properties is a good place to set a path and/or turn on / off a page or feature.

**Comment by wastevens** [comment]
That... could be tricky.

I would prefer to defer this question at the moment.  Presently, front end development can pull down the project and just focus on the UI elements (in the src/web directory)

**Comment by tsal** [comment]
We can address this later as a refactor project if it's determined using src/web/ as a location is unwieldy.
