### ISSUE TITLE
chargen fields not submitting

### ISSUE THREAD

**Issue by undergroundtheater** [wastevens/ElysiumFrontend#6]
we're still seeing development information in the bottom of the page, and certain dropdowns just do not update (or the submit button isn't working), none of which is a priority issue, but if we could update the JSP to not link to the chargen page and just allow base character "creation" (name + troupe) that should be enough.

**Comment by wastevens** [comment]
All of the fields should be updating in the next release.

Also, I disagree with the idea of removing the character management link.  For the first round of UAT testing, we need to emphasize that flushing out defects and improvements in the admin management is priority, but I don't want to discourage people from poking at stuff.

**Comment by wastevens** [comment]
Checked against UAT 18c38f6 - appears to have been resolved.
